services:
  - type: web
    name: hacknex-obsidian06
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://hacknex-obsidian.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://hacknex-obsidian.onrender.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://vrgendezcvpzjuhcuhfo.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyZ2VuZGV6Y3Zwemp1aGN1aGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgzNDU3MTcsImV4cCI6MjEwMzkyMTcxN30.Qfo4AkAFjWufF-IcCdHxV2cNFh5RmNRJfOUef3gXfIs
